# RTAB-Map конфигурация для Raspberry Pi с OAK-D-Lite
# Оптимизировано для работы на отдельной Raspberry Pi

# Глобальные параметры для всех нод
/**:
  ros__parameters:
    image_transport: compressed
    rgb_image_transport: compressed
    depth_image_transport: compressed

# Параметры rgbd_sync ноды
rgbd_sync:
  ros__parameters:
    image_transport: compressed
    rgb_image_transport: compressed
    depth_image_transport: compressed
    approx_sync: true
    queue_size: 10

# Параметры rgbd_odometry ноды
rgbd_odometry:
  ros__parameters:
    image_transport: compressed
    rgb_image_transport: compressed
    depth_image_transport: compressed
    approx_sync: true
    queue_size: 10

rtabmap:
  ros__parameters:
    
    # Базовые настройки
    frame_id: base_link
    map_frame_id: map
    odom_frame_id: odom
    publish_tf: true
    tf_delay: 0.05
    
    # Частота обработки (снижена для Pi)
    approx_sync: true
    queue_size: 5  # Уменьшен размер очереди
    
    # Используем сжатые изображения от OAK-D
    subscribe_depth: true
    subscribe_rgb: true
    subscribe_scan: false
    subscribe_scan_cloud: false
    subscribe_stereo: false
    
    # QoS настройки для работы через CycloneDDS между Pi
    qos: 1  # Reliable
    qos_image_transport: 1
    qos_scan: 1
    qos_odom: 1
    qos_imu: 1
    
    # Ремаппинг топиков с OAK-D
    # ВАЖНО: используем image_rect (ректифицированные изображения) а не image_raw
    # RectifyNode автоматически создаёт /compressed варианты через image_transport
    rgb/image: /camera/camera/color/image_rect
    rgb/camera_info: /camera/camera/color/camera_info
    depth/image: /camera/camera/depth/image_rect_raw
    depth/camera_info: /camera/camera/depth/camera_info
    
    # КРИТИЧНО: указываем использовать сжатые топики
    image_transport: compressed
    rgb_image_transport: compressed
    depth_image_transport: compressed
    
    # Параметры RTAB-Map для экономии ресурсов Pi
    Rtabmap/DetectionRate: "0.5"  # Обнаружение loop closures раз в 2 секунды
    Rtabmap/TimeThr: "0"  # Без ограничения времени
    Rtabmap/MemoryThr: "50"  # Ограничение памяти (50 МБ)
    Rtabmap/ImageBufferSize: "1"  # Минимальный буфер изображений
    
    # Оптимизация памяти
    Mem/IncrementalMemory: "true"
    Mem/InitWMWithAllNodes: "false"
    Mem/ReduceGraph: "true"
    Mem/NotLinkedNodesKept: "false"
    Mem/STMSize: "10"  # Краткосрочная память (10 локаций)
    Mem/LaserScanNormalK: "0"  # Отключено
    
    # Визуальная одометрия (VO) - оптимизировано для Pi
    Odom/Strategy: "0"  # Frame-to-Map = 0, Frame-to-Frame = 1
    Odom/ResetCountdown: "1"
    OdomF2M/MaxSize: "1000"
    Odom/ImageBufferSize: "1"
    
    # Оптимизация feature extraction для слабого CPU
    Vis/MinInliers: "10"  # Минимум inliers
    Vis/MaxFeatures: "400"  # СНИЖЕНО с 1000 до 400 для экономии CPU
    Vis/FeatureType: "6"  # 6=GFTT/BRIEF (быстрее чем SIFT/SURF)
    Vis/CorNNDR: "0.8"
    Vis/MaxDepth: "5.0"  # Максимальная глубина 5 метров
    Vis/MinDepth: "0.3"  # Минимальная глубина 30 см
    
    # Grid mapping (для навигации)
    Grid/FromDepth: "true"
    Grid/CellSize: "0.05"  # 5 см на ячейку
    Grid/RangeMax: "5.0"  # Максимальная дальность 5 метров
    Grid/ClusterRadius: "0.1"
    Grid/GroundIsObstacle: "false"
    Grid/MaxObstacleHeight: "2.0"
    Grid/MaxGroundHeight: "0.0"
    
    # Оптимизация графа
    RGBD/ProximityBySpace: "true"
    RGBD/ProximityMaxGraphDepth: "50"
    RGBD/ProximityPathMaxNeighbors: "1"
    RGBD/AngularUpdate: "0.05"  # 3 градуса
    RGBD/LinearUpdate: "0.05"  # 5 см
    RGBD/OptimizeFromGraphEnd: "false"
    RGBD/OptimizeMaxError: "1.0"
    
    # Loop closure detection - снижена нагрузка
    Kp/MaxFeatures: "200"  # СНИЖЕНО с 400 до 200
    Kp/DetectorStrategy: "6"  # GFTT (быстрее)
    Kp/WordsPerImage: "100"  # Слов на изображение
    
    # Database оптимизация
    DbSqlite3/InMemory: "false"
    DbSqlite3/CacheSize: "1000"  # Кеш SQLite
    DbSqlite3/JournalMode: "WAL"  # Write-Ahead Logging
    DbSqlite3/Synchronous: "NORMAL"
    DbSqlite3/TempStore: "MEMORY"
    
    # Публикация данных - минимизация
    Rtabmap/PublishStats: "true"
    Rtabmap/PublishLastSignature: "false"
    Rtabmap/PublishPdf: "false"
    Rtabmap/PublishLikelihood: "false"
    Rtabmap/PublishRAMUsage: "true"
