# twist_mux configuration для rob_box
# Мультиплексирование команд скорости с приоритизацией

twist_mux:
  ros__parameters:
    # Источники команд (в порядке приоритета - priority: 0-255, чем выше тем приоритетнее)
    topics:
      # 1. Emergency Stop (наивысший приоритет)
      emergency_stop:
        topic: cmd_vel_emergency
        timeout: 0.1
        priority: 255
        
      # 2. Joystick/Gamepad (высокий приоритет - оператор с физическим пультом)
      joystick:
        topic: cmd_vel_joy
        timeout: 0.5
        priority: 100
        
      # 3. Web UI / Mobile App (средний приоритет - оператор через веб)
      web_ui:
        topic: cmd_vel_web
        timeout: 1.0
        priority: 50
        
      # 4. Voice Commands (низкий-средний приоритет - может быть кто угодно)
      voice:
        topic: cmd_vel_voice
        timeout: 1.0
        priority: 25
        
      # 5. Nav2 Navigation (самый низкий приоритет - автономия)
      navigation:
        topic: cmd_vel
        timeout: 0.5
        priority: 10

    # Locks (блокировка определенных источников)
    # locks:
    #   manual_lock:
    #     topic: /manual_lock
    #     timeout: 5.0
    #     priority: 255
