version: '3.8'

services:    
  #  discovery:
  #    build:
  #      context: ./discovery
  #      dockerfile: Dockerfile
  #    container_name: fastdds-discovery
  #    network_mode: host
  #    restart: unless-stopped
  rtabmap:
    build: 
      context: ./rtabmap
      dockerfile: Dockerfile
    image: rtabmap-custom:latest
    container_name: rtabmap
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=0
      - QT_QPA_PLATFORM=offscreen
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///etc/cyclonedds.xml
      # Переменные для сжатия изображений
      - COMPRESSED_IMAGE_TRANSPORT_JPEG_QUALITY=80
      - COMPRESSED_DEPTH_IMAGE_TRANSPORT_PNG_LEVEL=3
    volumes:
      - ./config:/config
      - ./config/cyclonedds.xml:/etc/cyclonedds.xml
      - ./config/rtabmap_config.yaml:/config/rtabmap.yaml
      - ./maps:/maps
    # НОВАЯ команда - использует OAK-D топики и оптимизированный конфиг
    command: >
      ros2 launch rtabmap_launch rtabmap.launch.py
      params:=/config/rtabmap.yaml
      frame_id:=base_link
      use_sim_time:=false
      qos:=1
      approx_sync:=true
      approx_sync_max_interval:=0.1
      subscribe_rgb:=true
      subscribe_depth:=true
      subscribe_scan:=false
      subscribe_stereo:=false
      rgbd_sync:=true
      rgb_topic:=/oak/rgb/image_raw
      depth_topic:=/oak/stereo/image_raw
      camera_info_topic:=/oak/rgb/camera_info
      compressed:=true
      rtabmap_viz:=false
      rviz:=false
      visual_odometry:=true
      icp_odometry:=false
      odom_topic:=/odom
      wait_for_transform:=0.5
      database_path:=/maps/rtabmap.db
    restart: unless-stopped