version: '3.8'

# Использует переменные из .env файла:
# - ROS_DISTRO: версия ROS 2 (humble, jazzy, и т.д.)
# - IMAGE_TAG: тег ветки (latest, dev, rc-X.Y.Z)
# - BASE_IMAGE_PREFIX: ghcr.io/krikz/rob_box_base
# - SERVICE_IMAGE_PREFIX: ghcr.io/krikz/rob_box

services:
  # Zenoh Router - центральный роутер для связи между Pi
  zenoh-router:
    image: eclipse/zenoh:latest
    container_name: zenoh-router
    network_mode: host
    environment:
      - RUST_LOG=zenoh=info
    volumes:
      - ./config/zenoh_router_config.json5:/zenoh_config.json5
    command: -c /zenoh_config.json5
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/@/local/router || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 30s

  # Robot State Publisher - публикует TF дерево робота из URDF
  robot-state-publisher:
    image: ghcr.io/krikz/rob_box:robot-state-publisher-humble-latest
    container_name: robot-state-publisher
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_zenoh_cpp
      - RUST_LOG=zenoh=info
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
      - ZENOH_CONFIG=/config/shared/zenoh_session_config.json5
      - LD_LIBRARY_PATH=/opt/ros/humble/opt/zenoh_cpp_vendor/lib:/opt/ros/humble/lib/aarch64-linux-gnu:/opt/ros/humble/lib
    volumes:
      - ./config:/config/shared:ro
      - ./scripts/robot_state_publisher:/scripts:ro
    command: ["/scripts/start_robot_state_publisher.sh"]
    depends_on:
      - zenoh-router
    restart: unless-stopped
    
  rtabmap:
    image: ghcr.io/krikz/rob_box:rtabmap-humble-latest
    container_name: rtabmap
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=0
      - QT_QPA_PLATFORM=offscreen
      - RMW_IMPLEMENTATION=rmw_zenoh_cpp
      - ZENOH_ROUTER_CHECK_ATTEMPTS=10  # Подключаемся к локальному router
      - RUST_LOG=zenoh=info
      # Zenoh configuration через JSON
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
      - ZENOH_CONFIG=/config/shared/zenoh_session_config.json5
      # КРИТИЧНО: Путь к библиотекам Zenoh (vendor устанавливает в нестандартный путь)
      - LD_LIBRARY_PATH=/opt/ros/${ROS_DISTRO:-humble}/opt/zenoh_cpp_vendor/lib:/opt/ros/${ROS_DISTRO:-humble}/lib/aarch64-linux-gnu:/opt/ros/${ROS_DISTRO:-humble}/lib
    volumes:
      - ./config:/config/shared:ro
      - ./config/rtabmap:/config/rtabmap:ro
      - ./scripts/rtabmap:/scripts:ro
      - ./maps:/maps
    # Лидар режим: прямой запуск rtabmap через скрипт
    command: ["/scripts/start_rtabmap.sh"]
    depends_on:
      - zenoh-router
    restart: unless-stopped