version: '3.8'

services:    
  rtabmap:
    image: introlab3it/rtabmap_ros:humble
    container_name: rtabmap
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=0
      - QT_QPA_PLATFORM=offscreen  # Добавлено для headless режима
    volumes:
      - ./config/rtabmap_config.yaml:/config/rtabmap.yaml
      - ./maps:/maps
    command: >
      ros2 launch rtabmap_launch rtabmap.launch.py
      frame_id:=base_link
      stereo:=true
      left_image_topic:=/camera/camera/infra1/image_rect_raw
      right_image_topic:=/camera/camera/infra2/image_rect_raw
      left_camera_info_topic:=/camera/camera/infra1/camera_info
      right_camera_info_topic:=/camera/camera/infra2/camera_info
      subscribe_scan:=true
      scan_topic:=/scan
      visual_odometry:=false
      rtabmap_args:="--delete_db_on_start --Stereo/MaxDisparity 200 --Vis/CorFlowMaxLevel 5"
      compressed:=false  # Отключено сжатие
      approx_sync:=true
      wait_for_transform:=0.2
      rtabmapviz:=false  # Отключен GUI
      rviz:=false        # Отключен RViz
    restart: unless-stopped