version: '3.8'

services:
  # ROS 2 Zenoh Router - центральный роутер для связи между Pi
  zenoh-router:
    build:
      context: ./zenoh-router
      dockerfile: Dockerfile
    image: zenoh-router-main:latest
    container_name: zenoh-router
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=0
      - RUST_LOG=zenoh=info
      - ZENOH_CONFIG=/zenoh_config.json5
    volumes:
      - ./config/zenoh_router_config.json5:/zenoh_config.json5
      - /dev/shm:/dev/shm
    restart: unless-stopped
    
  #  discovery:
  #    build:
  #      context: ./discovery
  #      dockerfile: Dockerfile
  #    container_name: fastdds-discovery
  #    network_mode: host
  #    restart: unless-stopped
    
  rtabmap:
    build: 
      context: ./rtabmap
      dockerfile: Dockerfile
    image: rtabmap-custom:latest
    container_name: rtabmap
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=0
      - QT_QPA_PLATFORM=offscreen
      - RMW_IMPLEMENTATION=rmw_zenoh_cpp
      - ZENOH_ROUTER_CHECK_ATTEMPTS=10  # Подключаемся к локальному router
      - RUST_LOG=zenoh=info
      # Zenoh configuration через JSON
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
      - ZENOH_CONFIG=/config/zenoh_session_config.json5
      # КРИТИЧНО: Путь к библиотекам Zenoh (vendor устанавливает в нестандартный путь)
      - LD_LIBRARY_PATH=/opt/ros/humble/opt/zenoh_cpp_vendor/lib:/opt/ros/humble/lib/aarch64-linux-gnu:/opt/ros/humble/lib
      # Переменные для сжатия изображений
      - COMPRESSED_IMAGE_TRANSPORT_JPEG_QUALITY=80
      - COMPRESSED_DEPTH_IMAGE_TRANSPORT_PNG_LEVEL=3
    volumes:
      - ./config:/config
      - ./config/zenoh_session_config.json5:/config/zenoh_session_config.json5
      - ./config/rtabmap_config.yaml:/config/rtabmap.yaml
      - ./maps:/maps
    # Оптимизированная команда - прямое использование сжатых топиков от OAK-D
    command: >
      ros2 launch rtabmap_launch rtabmap.launch.py
      params:=/config/rtabmap.yaml
      frame_id:=base_link
      use_sim_time:=false
      qos:=1
      approx_sync:=true
      approx_sync_max_interval:=0.1
      subscribe_rgbd:=false
      subscribe_rgb:=true
      subscribe_depth:=true
      subscribe_scan:=false
      subscribe_stereo:=false
      rgbd_sync:=true
      rgb_topic:=/camera/camera/color/image_rect
      depth_topic:=/camera/camera/depth/image_rect_raw
      camera_info_topic:=/camera/camera/color/camera_info
      rtabmap_viz:=false
      rviz:=false
      visual_odometry:=true
      icp_odometry:=false
      odom_topic:=/odom
      wait_for_transform:=0.5
      database_path:=/maps/rtabmap.db
    depends_on:
      - zenoh-router
    restart: unless-stopped