version: '3.8'

# Использует переменные из .env файла:
# - ROS_DISTRO: версия ROS 2 (humble, jazzy, и т.д.)
# - IMAGE_TAG: тег ветки (latest, dev, rc-X.Y.Z)
# - BASE_IMAGE_PREFIX: ghcr.io/krikz/rob_box_base
# - SERVICE_IMAGE_PREFIX: ghcr.io/krikz/rob_box

services:
  # Zenoh Router - центральный роутер для связи между Pi
  zenoh-router:
    image: eclipse/zenoh:latest
    container_name: zenoh-router
    network_mode: host
    environment:
      - RUST_LOG=zenoh=info
    volumes:
      - ./config/zenoh_router_config.json5:/zenoh_config.json5
    command: -c /zenoh_config.json5
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/@/local/router || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 30s

  # Robot State Publisher - публикует TF дерево робота из URDF
  robot-state-publisher:
    image: ghcr.io/krikz/rob_box:robot-state-publisher-humble-latest
    container_name: robot-state-publisher
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_zenoh_cpp
      - RUST_LOG=zenoh=info
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
      - ZENOH_CONFIG=/config/shared/zenoh_session_config.json5
      - LD_LIBRARY_PATH=/opt/ros/humble/opt/zenoh_cpp_vendor/lib:/opt/ros/humble/lib/aarch64-linux-gnu:/opt/ros/humble/lib
    volumes:
      - ./config:/config/shared:ro
      - ./robot_state_publisher/scripts:/scripts:ro
    command: ["/scripts/start_robot_state_publisher.sh"]
    depends_on:
      - zenoh-router
    restart: unless-stopped
    
  rtabmap:
    image: ghcr.io/krikz/rob_box:rtabmap-humble-latest
    container_name: rtabmap
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=0
      - QT_QPA_PLATFORM=offscreen
      - RMW_IMPLEMENTATION=rmw_zenoh_cpp
      - ZENOH_ROUTER_CHECK_ATTEMPTS=10  # Подключаемся к локальному router
      - RUST_LOG=zenoh=info
      # Zenoh configuration через JSON
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
      - ZENOH_CONFIG=/config/shared/zenoh_session_config.json5
      # КРИТИЧНО: Путь к библиотекам Zenoh (vendor устанавливает в нестандартный путь)
      - LD_LIBRARY_PATH=/opt/ros/${ROS_DISTRO:-humble}/opt/zenoh_cpp_vendor/lib:/opt/ros/${ROS_DISTRO:-humble}/lib/aarch64-linux-gnu:/opt/ros/${ROS_DISTRO:-humble}/lib
    volumes:
      - ./config:/config/shared:ro
      - ./rtabmap/config:/config/rtabmap:ro
      - ./maps:/maps
    # Лидар + AprilTag режим: только LaserScan для навигации и маркеры для локализации
    command: >
      ros2 launch rtabmap_launch rtabmap.launch.py
      params:=/config/rtabmap/rtabmap.yaml
      frame_id:=base_link
      odom_frame_id:=odom
      use_sim_time:=false
      qos:=1
      approx_sync:=true
      approx_sync_max_interval:=0.2
      subscribe_rgbd:=false
      subscribe_rgb:=false
      subscribe_depth:=false
      subscribe_scan:=true
      subscribe_stereo:=false
      scan_topic:=/scan
      rtabmap_viz:=false
      rviz:=false
      visual_odometry:=false
      icp_odometry:=true
      odom_topic:=odom
      wait_for_transform:=0.5
      database_path:=/maps/rtabmap.db
    depends_on:
      - zenoh-router
    restart: unless-stopped