# RTAB-Map параметры для режима ТОЛЬКО LaserScan (без камеры)
# Оптимизировано для работы через Zenoh между Pi

/**:
  ros__parameters:
    queue_size: 10
    approx_sync: false  # Для LaserScan не требуется синхронизация

rtabmap:
  ros__parameters:
    # Основные параметры
    queue_size: 10
    
    # Режим работы: только LaserScan, без RGB-D
    Mem/IncrementalMemory: true
    Mem/InitWMWithAllNodes: false
    
    # LaserScan параметры - ВАЖНО: boolean без кавычек!
    subscribe_scan: true
    subscribe_rgbd: false
    subscribe_rgb: false
    subscribe_depth: false
    subscribe_stereo: false
    
    # Grid mapping параметры для лидара - строковые значения в кавычках
    Grid/FromDepth: "false"  # Не используем depth камеру
    Grid/CellSize: "0.05"    # 5см разрешение сетки
    Grid/RangeMax: "10.0"    # Используем лидар до 10м
    Grid/RangeMin: "0.2"     # Минимальная дистанция
    
    # Оптимизация для 2D лидара
    Reg/Strategy: "1"        # ICP (Iterative Closest Point)
    Icp/PointToPlane: "false"  # 2D ICP
    Icp/Iterations: "30"
    Icp/Epsilon: "0.001"
    Icp/MaxTranslation: "0.3"
    Icp/MaxRotation: "0.78"  # ~45 градусов
    Icp/CorrespondenceRatio: "0.4"
    
    # Loop closure для навигации
    Mem/LaserScanNormalK: "0"  # Отключено для 2D лидара
    RGBD/ProximityPathMaxNeighbors: "10"
    RGBD/OptimizeFromGraphEnd: "true"
