# Happy Emotion Animation (IMPROVED v2.5)
name: "happy"
description: "Happy emotion with gradient eyes, rainbow rear wheels, and curved smile"
version: "2.5"
author: "rob_box"

duration_ms: 3200
loop: true
fps: 10

fade_in_ms: 200
fade_out_ms: 200

panels:
  # Front wheels - gradient happy eyes with sparkles (4 frames)
  - logical_group: "wheel_front_left"
    offset_ms: 0
    frames:
      - image: "frames/emotions/eye_fl_happy_01.png"
        duration_ms: 800
      - image: "frames/emotions/eye_fl_happy_02.png"  # Sparkle frame
        duration_ms: 800
      - image: "frames/emotions/eye_fl_happy_03.png"
        duration_ms: 800
      - image: "frames/emotions/eye_fl_happy_04.png"
        duration_ms: 800

  - logical_group: "wheel_front_right"
    offset_ms: 0
    frames:
      - image: "frames/emotions/eye_fr_happy_01.png"
        duration_ms: 800
      - image: "frames/emotions/eye_fr_happy_02.png"  # Sparkle frame
        duration_ms: 800
      - image: "frames/emotions/eye_fr_happy_03.png"
        duration_ms: 800
      - image: "frames/emotions/eye_fr_happy_04.png"
        duration_ms: 800

  # Rear wheels - rainbow cycle (8 colors)
  - logical_group: "wheel_rear_left"
    offset_ms: 0
    frames:
      - image: "frames/emotions/wheel_rl_rainbow_01.png"  # Red
        duration_ms: 400
      - image: "frames/emotions/wheel_rl_rainbow_02.png"  # Orange
        duration_ms: 400
      - image: "frames/emotions/wheel_rl_rainbow_03.png"  # Yellow
        duration_ms: 400
      - image: "frames/emotions/wheel_rl_rainbow_04.png"  # Green
        duration_ms: 400
      - image: "frames/emotions/wheel_rl_rainbow_05.png"  # Cyan
        duration_ms: 400
      - image: "frames/emotions/wheel_rl_rainbow_06.png"  # Blue
        duration_ms: 400
      - image: "frames/emotions/wheel_rl_rainbow_07.png"  # Magenta
        duration_ms: 400
      - image: "frames/emotions/wheel_rl_rainbow_08.png"  # Pink
        duration_ms: 400

  - logical_group: "wheel_rear_right"
    offset_ms: 0
    frames:
      - image: "frames/emotions/wheel_rr_rainbow_01.png"
        duration_ms: 400
      - image: "frames/emotions/wheel_rr_rainbow_02.png"
        duration_ms: 400
      - image: "frames/emotions/wheel_rr_rainbow_03.png"
        duration_ms: 400
      - image: "frames/emotions/wheel_rr_rainbow_04.png"
        duration_ms: 400
      - image: "frames/emotions/wheel_rr_rainbow_05.png"
        duration_ms: 400
      - image: "frames/emotions/wheel_rr_rainbow_06.png"
        duration_ms: 400
      - image: "frames/emotions/wheel_rr_rainbow_07.png"
        duration_ms: 400
      - image: "frames/emotions/wheel_rr_rainbow_08.png"
        duration_ms: 400

  # Main display - curved smile (4 frames)
  - logical_group: "main_display"
    offset_ms: 0
    frames:
      - image: "frames/emotions/mouth_smile_01.png"
        duration_ms: 800
      - image: "frames/emotions/mouth_smile_02.png"
        duration_ms: 800
      - image: "frames/emotions/mouth_smile_03.png"
        duration_ms: 800
      - image: "frames/emotions/mouth_smile_04.png"
        duration_ms: 800

metadata:
  priority: "normal"
  category: "emotion"
  tags: ["happy", "smile", "positive", "emotion", "rainbow", "gradient"]
