version: '3.8'

services:
  oak-d:
    image: luxonis/depthai-ros:humble-latest
    container_name: oak-d
    network_mode: host
    devices:
      - /dev/vchiq:/dev/vchiq
    environment:
      - ROS_MASTER_URI=http://10.1.1.10:11311
      - ROS_DOMAIN_ID=0
    volumes:
      - ./config/oak_d_config.yaml:/config/oak_d.yaml
    command: ros2 launch oak_d oak_d.launch.py
    restart: unless-stopped