version: '3.8'

services:
  oak-d:
    build:
      context: .
      dockerfile: oak-d/Dockerfile
    container_name: oak-d
    network_mode: host
    privileged: true
    environment:
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=0
      - DISPLAY=:0
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ./config:/config
      - /dev/shm:/dev/shm
    restart: unless-stopped
    
  apriltag:
    build:
      context: .
      dockerfile: apriltag/Dockerfile
    container_name: apriltag
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=0
    volumes:
      - ./config:/config
      - /dev/shm:/dev/shm
    depends_on:
      oak-d:
        condition: service_started
    restart: unless-stopped