version: '3.8'

services:
  oak-d:
    image: luxonis/depthai-ros:humble-latest
    container_name: oak-d
    network_mode: host
    devices:
      - /dev/vchiq:/dev/vchiq
    environment:
      - ROS_MASTER_URI=http://10.1.1.10:11311
      - ROS_DOMAIN_ID=0
    volumes:
      - ./config/oak_d_config.yaml:/config/oak_d.yaml
    command: ros2 launch oak_d oak_d.launch.py
    restart: unless-stopped
    
  lidar:
    image: sllidar/sllidar-ros:humble
    container_name: lidar
    network_mode: host
    devices:
      - /dev/ttyUSB1:/dev/ttyUSB1
    environment:
      - ROS_MASTER_URI=http://10.1.1.10:11311
      - ROS_DOMAIN_ID=0
    volumes:
      - ./config/lidar_config.yaml:/config/lidar.yaml
    command: ros2 launch lidar rplidar.launch.py
    restart: unless-stopped
    
  apriltag:
    image: apriltag/apriltag-ros:humble
    container_name: apriltag
    network_mode: host
    environment:
      - ROS_MASTER_URI=http://10.1.1.10:11311
      - ROS_DOMAIN_ID=0
    volumes:
      - ./config/apriltag_config.yaml:/config/apriltag.yaml
    command: ros2 launch apriltag apriltag.launch.py
    restart: unless-stopped
    
  led-matrix:
    image: led-matrix:latest
    container_name: led-matrix
    network_mode: host
    devices:
      - /dev/spidev0.0:/dev/spidev0.0
    environment:
      - ROS_MASTER_URI=http://10.1.1.10:11311
      - ROS_DOMAIN_ID=0
    volumes:
      - ./config/led_matrix_config.yaml:/config/panels.yaml
    command: ros2 launch led_matrix led_matrix_compositor_launch.py
    restart: unless-stopped
    
  microphone:
    image: respeaker:latest
    container_name: microphone
    network_mode: host
    devices:
      - /dev/snd:/dev/snd
    environment:
      - ROS_MASTER_URI=http://10.1.1.10:11311
      - ROS_DOMAIN_ID=0
    command: ros2 launch microphone respeaker.launch.py
    restart: unless-stopped