version: '3.8'

services:
  # Zenoh Router - локальный роутер для Vision Pi, подключается к Main Pi
  zenoh-router:
    image: eclipse/zenoh:latest
    container_name: zenoh-router-vision
    network_mode: host
    environment:
      - RUST_LOG=zenoh=info
    volumes:
      - ./config/zenoh_router_config.json5:/zenoh_config.json5
    command: -c /zenoh_config.json5
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/@/local/router || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 30s

  oak-d:
    image: ghcr.io/krikz/rob_box:oak-d-humble-latest
    container_name: oak-d
    network_mode: host
    privileged: true
    environment:
      - ROS_DOMAIN_ID=0
      - DISPLAY=:0
      - RMW_IMPLEMENTATION=rmw_zenoh_cpp
      - ZENOH_ROUTER_CHECK_ATTEMPTS=10  # Пытаемся подключиться к router 10 раз
      - RUST_LOG=zenoh=info  # Логирование Zenoh для отладки
      # Zenoh configuration через JSON - подключение к ЛОКАЛЬНОМУ роутеру Vision Pi
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
      - ZENOH_CONFIG=/config/shared/zenoh_session_config.json5
      - LD_LIBRARY_PATH=/opt/ros/humble/opt/zenoh_cpp_vendor/lib:/opt/ros/humble/lib/aarch64-linux-gnu:/opt/ros/humble/lib
    volumes:
      - ./config:/config/shared:ro
      - ./config/oak-d:/config/oak-d:ro
      - ./scripts/oak-d:/scripts:ro
      - ./oak-d/launch:/oak-d/launch:ro
      - /dev/bus/usb:/dev/bus/usb
      - /dev/shm:/dev/shm
    # AprilTag-only mode: OAK-D publishes only color image and camera_info for marker detection
    mem_limit: 6g  # Максимум 6GB (оставляем 2GB для системы)
    memswap_limit: 7g  # 6GB RAM + 1GB swap максимум
    command: ["/scripts/start_oak_d.sh"]
    depends_on:
      - zenoh-router
    restart: unless-stopped
    
  lslidar:
    image: ghcr.io/krikz/rob_box:lslidar-humble-latest
    container_name: lslidar
    network_mode: host
    privileged: true  # Для доступа к USB/Serial устройству
    devices:
      - /dev/ttyACM0:/dev/ttyACM0  # LSLIDAR N10 USB CDC ACM device
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_zenoh_cpp
      - ZENOH_ROUTER_CHECK_ATTEMPTS=10
      - RUST_LOG=zenoh=info
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
      - ZENOH_CONFIG=/config/shared/zenoh_session_config.json5
    volumes:
      - ./config:/config/shared:ro
      - ./config/lslidar:/config/lslidar:ro
      - ./scripts/lslidar:/scripts:ro
      - /dev/shm:/dev/shm
    command: ["/scripts/start_lslidar.sh"]
    depends_on:
      - zenoh-router
    restart: unless-stopped

  apriltag:
    image: ghcr.io/krikz/rob_box:apriltag-humble-latest
    container_name: apriltag
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_zenoh_cpp
      - ZENOH_ROUTER_CHECK_ATTEMPTS=10
      - RUST_LOG=zenoh=info
      # Zenoh configuration через JSON - подключение к ЛОКАЛЬНОМУ роутеру Vision Pi
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
      - ZENOH_CONFIG=/config/shared/zenoh_session_config.json5
    volumes:
      - ./config:/config/shared:ro
      - ./config/apriltag:/config/apriltag:ro
      - ./scripts/apriltag:/scripts:ro
      - /dev/shm:/dev/shm
    command: ["/scripts/start_apriltag.sh"]
    depends_on:
      - zenoh-router
      - oak-d
    restart: unless-stopped

  led-matrix:
    image: ghcr.io/krikz/rob_box:led-matrix-humble-latest
    container_name: led-matrix
    network_mode: host
    privileged: true  # Для доступа к SPI (/dev/spidev0.0)
    devices:
      - /dev/spidev0.0:/dev/spidev0.0  # SPI для NeoPixel LED
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_zenoh_cpp
      - ZENOH_ROUTER_CHECK_ATTEMPTS=10
      - RUST_LOG=zenoh=info
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
      - ZENOH_CONFIG=/config/shared/zenoh_session_config.json5
    volumes:
      - ./config:/config/shared:ro
      - ./config/led_matrix:/config/led_matrix:ro
      - ./scripts/led_matrix:/scripts:ro
    command: ["/scripts/start_led_matrix.sh"]
    depends_on:
      - zenoh-router
    restart: unless-stopped