version: '3.8'

services:
  oak-d:
    image: luxonis/depthai-ros:humble-latest
    container_name: oak-d
    network_mode: host
    privileged: true
    environment:
      - ROS_DOMAIN_ID=0
      - DISPLAY=:0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ./config:/config  # Монтируем всю папку конфигов
      - /dev/shm:/dev/shm
    command: >
      bash -c "source /opt/ros/humble/setup.bash && 
      ros2 launch depthai_ros_driver camera.launch.py 
      params_file:=/config/oak_d_config.yaml
      rs_compat:=true"
    restart: unless-stopped
    
  apriltag:
    image: husarion/apriltag:humble
    container_name: apriltag
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=0
    volumes:
      - ./config:/config
      - /dev/shm:/dev/shm
    command: >
      bash -c "source /opt/ros/humble/setup.bash && 
      ros2 run apriltag_ros apriltag_node --ros-args
      -r image_rect:=/camera/camera/color/image_rect
      -r camera_info:=/camera/camera/color/camera_info
      --params-file /config/apriltag_config.yaml"
    restart: unless-stopped
    depends_on:
      - oak-d
  zenoh-router:
    image: eclipse/zenoh:1.3.4
    container_name: zenoh-router
    ports:
      - "7447:7447/tcp"
      - "8000:8000"
    volumes:
      - ./config/router-config.json5:/router-config.json5
    command: ["-c", "/router-config.json5"]
    networks:
      - zenoh-net
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/@/local/router || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 30s
    restart: unless-stopped