version: '3.8'

services:
  # Zenoh Router - локальный роутер для Vision Pi, подключается к Main Pi
  zenoh-router:
    image: eclipse/zenoh:latest
    container_name: zenoh-router-vision
    network_mode: host
    environment:
      - RUST_LOG=zenoh=info
    volumes:
      - ./config/zenoh_router_config.json5:/zenoh_config.json5      
      - /dev/shm:/dev/shm
    command: -c /zenoh_config.json5
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/@/local/router || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 30s

  oak-d:
    build:
      context: .
      dockerfile: oak-d/Dockerfile
    container_name: oak-d
    network_mode: host
    privileged: true
    environment:
      - ROS_DOMAIN_ID=0
      - DISPLAY=:0
      - RMW_IMPLEMENTATION=rmw_zenoh_cpp
      - ZENOH_ROUTER_CHECK_ATTEMPTS=10  # Пытаемся подключиться к router 10 раз
      - RUST_LOG=zenoh=info  # Логирование Zenoh для отладки
      # Zenoh configuration через JSON - подключение к ЛОКАЛЬНОМУ роутеру Vision Pi
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
      - ZENOH_CONFIG=/config/zenoh_session_config.json5
    volumes:
      - ./config:/config
      - ./config/zenoh_session_config.json5:/config/zenoh_session_config.json5
      - /dev/bus/usb:/dev/bus/usb
      - /dev/shm:/dev/shm
    # КРИТИЧНО: Ограничение памяти для защиты от OOM на Pi (8GB RAM total)
    mem_limit: 6g  # Максимум 6GB (оставляем 2GB для системы)
    memswap_limit: 7g  # 6GB RAM + 1GB swap максимум
    depends_on:
      - zenoh-router
    restart: unless-stopped
    
  lslidar:
    build:
      context: .
      dockerfile: lslidar/Dockerfile
    container_name: lslidar
    network_mode: host
    privileged: true  # Для доступа к USB/Serial устройству
    devices:
      - /dev/ttyACM0:/dev/ttyACM0  # LSLIDAR N10 USB CDC ACM device
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_zenoh_cpp
      - ZENOH_ROUTER_CHECK_ATTEMPTS=10
      - RUST_LOG=zenoh=info
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
      - ZENOH_CONFIG=/config/zenoh_session_config.json5
    volumes:
      - ./config:/config
      - ./config/zenoh_session_config.json5:/config/zenoh_session_config.json5
      - /dev/shm:/dev/shm
    depends_on:
      - zenoh-router
    restart: unless-stopped

  apriltag:
    build:
      context: .
      dockerfile: apriltag/Dockerfile
    container_name: apriltag
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_zenoh_cpp
      - ZENOH_ROUTER_CHECK_ATTEMPTS=10
      - RUST_LOG=zenoh=info
      # Zenoh configuration через JSON - подключение к ЛОКАЛЬНОМУ роутеру Vision Pi
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
      - ZENOH_CONFIG=/config/zenoh_session_config.json5
    volumes:
      - ./config:/config
      - ./config/zenoh_session_config.json5:/config/zenoh_session_config.json5
      - /dev/shm:/dev/shm
    depends_on:
      - zenoh-router
      - oak-d
    restart: unless-stopped