version: '3.8'

services:
  oak-d:
    build:
      context: .
      dockerfile: oak-d/Dockerfile
    container_name: oak-d
    network_mode: host
    privileged: true
    environment:
      - ROS_DOMAIN_ID=0
      - DISPLAY=:0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///etc/cyclonedds.xml
    volumes:
      - ./config/cyclonedds.xml:/etc/cyclonedds.xml
      - /dev/bus/usb:/dev/bus/usb
      - ./config:/config
      - /dev/shm:/dev/shm
    command: >
      bash -c "source /opt/ros/humble/setup.bash && 
      ros2 launch depthai_ros_driver camera.launch.py 
      params_file:=/config/oak_d_config.yaml
      rs_compat:=true"
    restart: unless-stopped
    
  apriltag:
    build:
      context: .
      dockerfile: apriltag/Dockerfile
    container_name: apriltag
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///etc/cyclonedds.xml
    volumes:
      - ./config/cyclonedds.xml:/etc/cyclonedds.xml
      - ./config:/config
      - /dev/shm:/dev/shm
    depends_on:
      oak-d:
        condition: service_started
    restart: unless-stopped