# Local Costmap Configuration для rob_box
# Локальная карта препятствий вокруг робота

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: False
      rolling_window: True
      width: 3  # 3 метра вокруг робота
      height: 3
      resolution: 0.05  # 5см на ячейку
      robot_radius: 0.17  # 170мм радиус
      plugins: ["voxel_layer", "inflation_layer"]
      
      # Фильтры (если нужны)
      filters: []
      
      # Voxel Layer - 3D препятствия из сканов
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      
      # Static Layer отключен для локальной карты
      static_layer:
        enabled: False
      
      # Inflation Layer - расширение препятствий
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55  # Безопасное расстояние (robot_radius + margin)
      
      always_send_full_costmap: True
