apriltag:
  ros__parameters:
    # Основные параметры
    image_transport: raw
    family: 36h11          # Семейство тегов (стандартное)
    size: 0.16             # Размер тега в метрах (16 см)
    profile: false         # Отключить профилирование
    
    # Параметры детекции
    max_hamming: 0         # Максимальное количество исправленных бит
    detector:
      threads: 2           # Используем 2 потока для лучшей производительности на Pi
      decimate: 1.0        # Не уменьшать разрешение (OAK-D и так не самая мощная камера)
      blur: 0.0            # Без размытия
      refine: true         # Уточнение границ
      sharpening: 0.25     # Умеренное повышение резкости
      debug: false             # Отключить отладочные изображения
    
    # Метод оценки позы
    pose_estimation_method: "pnp"  # Используем метод PnP
    
    # Опционально: настройка конкретных тегов
    # tag:
    #   ids: [0, 1, 2, 3]
    #   frames: ["tag0", "tag1", "tag2", "tag3"]
    #   sizes: [0.16, 0.16, 0.16, 0.16]