<?xml version="1.0"?>
<robot name="rob_box" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<!-- Переменные -->
	<xacro:property name="base_size" value="0.4757 0.238 0.1885"/>
	<xacro:property name="wheel_radius" value="0.115"/>
	<xacro:property name="wheel_length" value="0.05"/>
	<xacro:property name="rocker_length" value="0.28934"/>
	<xacro:property name="rocker_width" value="0.05"/>
	<xacro:property name="rocker_thickness" value="0.01"/>
	<xacro:property name="wheel_mass" value="2"/>
	<xacro:property name="rocker_mass" value="3"/>
	<xacro:property name="base_mass" value="10"/>

	<!-- Основное шасси -->
	<link name="base_link">
		<visual>
			<origin xyz="0 0 0.0565" rpy="0 0 0"/>
			<geometry>
				<box size="${base_size}"/>
			</geometry>
			<material name="white">
				<color rgba="1 1 1 1"/>
			</material>
		</visual>
		<!-- Меш body_case.stl -->
		<visual>
			<origin xyz="0 -0.18 -0.02" rpy="0 0 -1.5708"/>
			<geometry>
				<mesh filename="package://rob_box_description/meshes/body_case.stl" scale="0.001 0.001 0.001"/>
			</geometry>
			<material name="silver">
				<color rgba="0.75 0.75 0.75 1"/>
			</material>
		</visual>
		<collision>
			<origin xyz="0 0 0.0565" rpy="0 0 0"/>
			<geometry>
				<box size="${base_size}"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="${base_mass}"/>
			<origin xyz="0 0 0.0565"/>
			<inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
		</inertial>
	</link>

	<!-- Макросы -->
	<xacro:macro name="wheel" params="name parent_link origin_xyz rotation_z side">
		<link name="${name}">
			<visual>
				<origin xyz="${-0.0035*side} 0 0.1451" rpy="1.5708 0 ${rotation_z}"/>
				<geometry>
					<mesh filename="package://rob_box_description/meshes/wheel.stl" scale="0.001 0.001 0.001"/>
				</geometry>
				<material name="black">
					<color rgba="0 0 0 1"/>
				</material>
			</visual>
			<collision>
				<origin xyz="0 ${0.05*side} 0" rpy="1.5708 0 0"/>
				<geometry>
					<cylinder radius="${wheel_radius}" length="${wheel_length}"/>
				</geometry>
			</collision>
			<inertial>
				<mass value="${wheel_mass}"/>
				<origin xyz="0 0 0"/>
				<inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
			</inertial>
		</link>
		<joint name="${name}_joint" type="continuous">
			<parent link="${parent_link}"/>
			<child link="${name}"/>
			<origin xyz="${origin_xyz}" rpy="0 0 0"/>
			<axis xyz="0 1 0"/>
		</joint>
	</xacro:macro>

	<xacro:macro name="rocker" params="name side side_x">
		<link name="${name}">
			<visual>
				<origin xyz="0 0 -0.11" rpy="0 3.1416 -1.5708"/>
				<geometry>
					<mesh filename="package://rob_box_description/meshes/rocker.stl" scale="${side * 0.001} 0.001 0.001"/>
				</geometry>
				<material name="silver">
					<color rgba="0.5 0.5 0.5 1"/>
				</material>
			</visual>
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<box size="${rocker_length} ${rocker_width} ${rocker_thickness}"/>
				</geometry>
			</collision>
			<inertial>
				<mass value="${rocker_mass}"/>
				<origin xyz="0 0 0"/>
				<inertia ixx="0.02" ixy="0" ixz="0" iyy="0.02" iyz="0" izz="0.02"/>
			</inertial>
		</link>
		<joint name="${name}_joint" type="fixed">
			<parent link="base_link"/>
			<child link="${name}"/>
			<origin xyz="0 ${side * 0.23048 + side_x} 0.09425" rpy="0 0 0"/>
			<axis xyz="0 1 0"/>
			<limit effort="10" velocity="1" lower="-0.3" upper="0.3"/>
		</joint>
	</xacro:macro>

	<!-- Сенсоры -->
	<xacro:macro name="lidar" params="name parent_link origin_xyz topic_name">
		<link name="${name}">
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<cylinder radius="0.026" length="0.0361"/>
				</geometry>
				<material name="black">
					<color rgba="0 0 0 1"/>
				</material>
			</visual>
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<cylinder radius="0.026" length="0.0361"/>
				</geometry>
			</collision>
			<inertial>
				<mass value="0.06"/>
				<origin xyz="0 0 0"/>
				<inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
			</inertial>
		</link>
		<joint name="${name}_joint" type="fixed">
			<parent link="${parent_link}"/>
			<child link="${name}"/>
			<origin xyz="${origin_xyz}" rpy="0 0 0"/>
		</joint>
		<gazebo reference="${name}">
			<sensor name="${name}_sensor" type="gpu_lidar">
				<pose>0 0 0 0 0 0</pose>
				<topic>${topic_name}</topic>
				<update_rate>10</update_rate>
				<ray>
					<scan>
						<horizontal>
							<samples>640</samples>
							<resolution>1</resolution>
							<min_angle>-1.396263</min_angle>
							<max_angle>1.396263</max_angle>
						</horizontal>
						<vertical>
							<samples>1</samples>
							<resolution>0.01</resolution>
							<min_angle>0</min_angle>
							<max_angle>0</max_angle>
						</vertical>
					</scan>
					<range>
						<min>0.08</min>
						<max>10.0</max>
						<resolution>0.01</resolution>
					</range>
				</ray>
				<always_on>1</always_on>
				<visualize>true</visualize>
			</sensor>
			<plugin filename="libignition-gazebo-sensors-system.so" name="ignition::gazebo::systems::Sensors">
				<render_engine>ogre2</render_engine>
			</plugin>
		</gazebo>
	</xacro:macro>

	<!-- OAK-D Camera Macro - соответствует реальной структуре фреймов depthai_ros_driver -->
	<xacro:macro name="oak_d_camera" params="name parent_link origin_xyz origin_rpy">
		<!-- camera_link - основной корпус камеры -->
		<link name="${name}_link">
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<box size="0.097 0.0275 0.0214"/>  <!-- Размеры OAK-D-Lite -->
				</geometry>
				<material name="dark_grey">
					<color rgba="0.2 0.2 0.2 1"/>
				</material>
			</visual>
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<box size="0.097 0.0275 0.0214"/>
				</geometry>
			</collision>
			<inertial>
				<mass value="0.061"/>  <!-- 61g вес OAK-D-Lite -->
				<origin xyz="0 0 0"/>
				<inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
			</inertial>
		</link>

		<!-- Присоединение к роботу -->
		<joint name="${name}_joint" type="fixed">
			<parent link="${parent_link}"/>
			<child link="${name}_link"/>
			<origin xyz="${origin_xyz}" rpy="${origin_rpy}"/>
		</joint>

		<!-- camera (intermediate frame - используется depthai_ros_driver) -->
		<link name="${name}"/>
		<joint name="${name}_base_joint" type="fixed">
			<parent link="${name}_link"/>
			<child link="${name}"/>
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</joint>

		<!-- Color camera frames -->
		<link name="${name}_color_frame"/>
		<joint name="${name}_color_frame_joint" type="fixed">
			<parent link="${name}"/>
			<child link="${name}_color_frame"/>
			<!-- Смещение RGB камеры относительно базы (из calibration) -->
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</joint>

		<link name="${name}_color_optical_frame"/>
		<joint name="${name}_color_optical_frame_joint" type="fixed">
			<parent link="${name}_color_frame"/>
			<child link="${name}_color_optical_frame"/>
			<!-- Optical frame: X right, Y down, Z forward (ROS camera convention) -->
			<origin xyz="0 0 0" rpy="-1.5708 0 -1.5708"/>
		</joint>

		<!-- Depth/Stereo camera frames -->
		<link name="${name}_depth_frame"/>
		<joint name="${name}_depth_frame_joint" type="fixed">
			<parent link="${name}"/>
			<child link="${name}_depth_frame"/>
			<!-- Depth камера немного смещена (левая камера stereo пары) -->
			<origin xyz="0 0.0375 0" rpy="0 0 0"/>
		</joint>

		<link name="${name}_depth_optical_frame"/>
		<joint name="${name}_depth_optical_frame_joint" type="fixed">
			<parent link="${name}_depth_frame"/>
			<child link="${name}_depth_optical_frame"/>
			<origin xyz="0 0 0" rpy="-1.5708 0 -1.5708"/>
		</joint>

		<!-- IMU frame (если используется) -->
		<link name="${name}_imu_frame"/>
		<joint name="${name}_imu_frame_joint" type="fixed">
			<parent link="${name}"/>
			<child link="${name}_imu_frame"/>
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</joint>
	</xacro:macro>

	<!-- Использование макросов -->
	<xacro:rocker name="left_rocker" side="1" side_x="-0.05"/>
	<xacro:rocker name="right_rocker" side="-1" side_x="0.05"/>
	<xacro:wheel name="left_front_wheel" parent_link="left_rocker" origin_xyz="0.14467 0 -0.11" rotation_z="1.5708" side="1"/>
	<xacro:wheel name="left_rear_wheel" parent_link="left_rocker" origin_xyz="-0.14467 0 -0.11" rotation_z="1.5708" side="1"/>
	<xacro:wheel name="right_front_wheel" parent_link="right_rocker" origin_xyz="0.14467 0 -0.11" rotation_z="-1.5708" side="-1"/>
	<xacro:wheel name="right_rear_wheel" parent_link="right_rocker" origin_xyz="-0.14467 0 -0.11" rotation_z="-1.5708" side="-1"/>

	<!-- Сенсоры -->
	<xacro:lidar name="lslidar_n10" parent_link="base_link" origin_xyz="0.25 0 0.2" topic_name="/scan"/>
	<!-- OAK-D-Lite камера на передней части робота -->
	<xacro:oak_d_camera name="camera" parent_link="base_link" origin_xyz="0.25 0 0.167" origin_rpy="0 0 0"/>

	<!-- ros2_control Hardware Interface - VESC Nexus -->
	<xacro:include filename="$(find rob_box_description)/urdf/rob_box_ros2_control.xacro"/>
</robot>