"""
music_library.py — Generated-music library for MiniMax Music API tracks.

Persists AI-generated MP3 tracks (with metadata) on the ``/data`` volume so
they survive container recreation.  Provides CRUD + FTS5 keyword search +
optional vector search via the existing :class:`OllamaEmbedder`.

This module is intentionally separate from the Renardo ``TrackLibrary`` in
``rob_box_mcp_tools.tools.music`` (which stores FoxDot code).  The two
stores serve different purposes:

  - ``TrackLibrary``     — Renardo code, played live via SuperCollider
  - ``GeneratedMusicLibrary`` — MP3 audio files generated by MiniMax Music

Both share the ``voice_memory.db`` SQLite file via the migrations dir
(``/data/voice_memory.db``), so operators only need to back up one file.

Schema is owned by ``migrations/007_generated_music_library.sql`` (v7).
The class also falls back to an inline schema for tests and offline runs
where the migrations directory is unavailable.

Public API:
    GeneratedMusicLibrary   — main class
    GeneratedTrack          — typed record returned by CRUD ops

Usage in MusicSkill:
    lib = GeneratedMusicLibrary("/data/music_library", "/data/voice_memory.db")
    meta = lib.save(track_id=uuid, prompt=..., lyrics=..., file_path=..., ...)
    found = lib.search("про дождь", limit=5)
    for track in lib.list_recent(limit=20):
        print(track.name, track.prompt)
"""

from __future__ import annotations

import json
import logging
import os
import sqlite3
import threading
import time
import uuid
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Data class
# ---------------------------------------------------------------------------


@dataclass
class GeneratedTrack:
    """One MP3 track generated by the MiniMax Music API.

    Mirrors the ``tracks`` table schema (migrations/007_generated_music_library.sql).
    """

    track_id: str
    name: str = ""
    prompt: str = ""
    lyrics: str = ""
    model: str = ""
    file_path: str = ""
    duration_s: float = 0.0
    file_size: int = 0
    mood: str = ""
    genre: str = ""
    lang: str = ""
    tags: List[str] = field(default_factory=list)
    play_count: int = 0
    generated_at: float = 0.0  # unix epoch
    updated_at: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    def to_json_safe(self) -> Dict[str, Any]:
        """Return JSON-safe dict (tags as list, not str)."""
        return self.to_dict()


# ---------------------------------------------------------------------------
# Library class
# ---------------------------------------------------------------------------


class GeneratedMusicLibrary:
    """Persistent store for MiniMax-generated MP3 tracks.

    Args:
        library_root: Directory on a persistent volume where MP3 files live.
                      One sub-directory per track (``<track_id>/track.mp3``).
        db_path:      Absolute path to the SQLite index file.  Typically
                      ``/data/voice_memory.db`` (shared with VoiceMemory).
        migrations_dir: Override path to the migrations directory.
        ollama_base_url: Ollama endpoint for semantic embeddings.
        ollama_model:    Embedding model (default ``nomic-embed-text``).
    """

    FTS_MIN_RESULTS = 3  # If FTS5 returns fewer, supplement with vector search

    def __init__(
        self,
        library_root=None,
        db_path=None,
        *,
        migrations_dir: Optional[str] = None,
        ollama_base_url: Optional[str] = None,
        ollama_model: str = "nomic-embed-text",
        ollama_timeout: float = 5.0,
    ) -> None:
        if library_root is None:
            library_root = os.getenv("MUSIC_LIBRARY_ROOT", "/data/music_library")
        if db_path is None:
            db_path = os.getenv("VOICE_MEMORY_DB_PATH", "/data/voice_memory.db")
        self.library_root = Path(library_root)
        self.db_path = db_path
        self.library_root.mkdir(parents=True, exist_ok=True)
        os.makedirs(os.path.dirname(os.path.abspath(db_path)) or ".", exist_ok=True)

        self.lock = threading.Lock()
        self.conn = sqlite3.connect(db_path, check_same_thread=False, timeout=10.0)
        self.conn.row_factory = sqlite3.Row

        with self.lock:
            self.conn.execute("PRAGMA foreign_keys = ON")
            self.conn.execute("PRAGMA journal_mode = WAL")
            self.conn.execute("PRAGMA synchronous = NORMAL")

        # Resolve migrations dir (4 levels up from core/ → project root/migrations),
        # matching the convention used by voice_memory.VoiceMemory.
        if migrations_dir:
            self.migrations_dir = migrations_dir
        else:
            self.migrations_dir = os.path.normpath(
                os.path.join(
                    os.path.dirname(__file__),
                    "..", "..", "..", "..",
                    "migrations",
                )
            )

        # Apply pending migrations (idempotent)
        self._run_migrations()

        # Best-effort Ollama embedder (lazy; safe if Ollama is down)
        self._embedder = None
        try:
            from .voice_memory import OllamaEmbedder

            self._embedder = OllamaEmbedder(
                base_url=ollama_base_url
                or os.getenv("OLLAMA_BASE_URL", "http://localhost:11434"),
                model=ollama_model,
                timeout=ollama_timeout,
            )
        except Exception as exc:  # noqa: BLE001
            logger.debug("OllamaEmbedder not available for music library: %s", exc)

        # Auto-embed a track when its vector is missing (best-effort, non-blocking).
        self._auto_embed = os.getenv("MUSIC_LIBRARY_AUTO_EMBED", "1") == "1"

    # ------------------------------------------------------------------
    # Schema management
    # ------------------------------------------------------------------

    def _run_migrations(self) -> None:
        """Apply pending SQL migrations (tracked by PRAGMA user_version)."""
        if not os.path.isdir(self.migrations_dir):
            self._create_inline_schema()
            return

        with self.lock:
            try:
                current = self.conn.execute("PRAGMA user_version").fetchone()[0]
            except sqlite3.DatabaseError:
                # Empty/corrupt file — start fresh at version 0
                current = 0

        for fname in sorted(f for f in os.listdir(self.migrations_dir) if f.endswith(".sql")):
            try:
                ver = int(fname.split("_", 1)[0])
            except ValueError:
                continue
            if ver <= current:
                continue
            sql_path = os.path.join(self.migrations_dir, fname)
            try:
                with open(sql_path, "r", encoding="utf-8") as fh:
                    sql = fh.read()
                with self.lock, self.conn:
                    self.conn.executescript(sql)
                    self.conn.execute(f"PRAGMA user_version = {ver}")
                logger.info("✅ Applied migration %s (PRAGMA user_version → %d)", fname, ver)
            except Exception as exc:  # noqa: BLE001
                logger.error("❌ Failed to apply migration %s: %s", fname, exc)
                raise

    def _create_inline_schema(self) -> None:
        """Inline schema (used when migrations/ is missing — tests, offline)."""
        schema = """
        CREATE TABLE IF NOT EXISTS generated_tracks (
            track_id    TEXT PRIMARY KEY,
            name        TEXT NOT NULL DEFAULT '',
            prompt      TEXT NOT NULL DEFAULT '',
            lyrics      TEXT NOT NULL DEFAULT '',
            model       TEXT NOT NULL DEFAULT '',
            file_path   TEXT NOT NULL DEFAULT '',
            duration_s  REAL NOT NULL DEFAULT 0,
            file_size   INTEGER NOT NULL DEFAULT 0,
            mood        TEXT NOT NULL DEFAULT '',
            genre       TEXT NOT NULL DEFAULT '',
            lang        TEXT NOT NULL DEFAULT '',
            tags        TEXT NOT NULL DEFAULT '[]',
            play_count  INTEGER NOT NULL DEFAULT 0,
            generated_at REAL NOT NULL,
            updated_at   REAL NOT NULL
        );

        CREATE INDEX IF NOT EXISTS idx_gt_generated_at ON generated_tracks(generated_at DESC);
        CREATE INDEX IF NOT EXISTS idx_gt_play_count  ON generated_tracks(play_count DESC);
        CREATE INDEX IF NOT EXISTS idx_gt_mood        ON generated_tracks(mood);
        CREATE INDEX IF NOT EXISTS idx_gt_genre       ON generated_tracks(genre);

        CREATE VIRTUAL TABLE IF NOT EXISTS generated_tracks_fts USING fts5(
            prompt, lyrics, name, mood, genre, tags,
            content = 'generated_tracks',
            content_rowid = 'rowid',
            tokenize = 'unicode61'
        );

        CREATE TRIGGER IF NOT EXISTS generated_tracks_ai AFTER INSERT ON generated_tracks BEGIN
            INSERT INTO generated_tracks_fts(rowid, prompt, lyrics, name, mood, genre, tags)
            VALUES (new.rowid, new.prompt, new.lyrics, new.name, new.mood, new.genre, new.tags);
        END;

        CREATE TRIGGER IF NOT EXISTS generated_tracks_au AFTER UPDATE ON generated_tracks BEGIN
            INSERT INTO generated_tracks_fts(generated_tracks_fts, rowid, prompt, lyrics, name, mood, genre, tags)
            VALUES ('delete', old.rowid, old.prompt, old.lyrics, old.name, old.mood, old.genre, old.tags);
            INSERT INTO generated_tracks_fts(rowid, prompt, lyrics, name, mood, genre, tags)
            VALUES (new.rowid, new.prompt, new.lyrics, new.name, new.mood, new.genre, new.tags);
        END;

        CREATE TRIGGER IF NOT EXISTS generated_tracks_ad AFTER DELETE ON generated_tracks BEGIN
            INSERT INTO generated_tracks_fts(generated_tracks_fts, rowid, prompt, lyrics, name, mood, genre, tags)
            VALUES ('delete', old.rowid, old.prompt, old.lyrics, old.name, old.mood, old.genre, old.tags);
        END;
        """
        with self.lock, self.conn:
            self.conn.executescript(schema)

    # ------------------------------------------------------------------
    # Path helpers
    # ------------------------------------------------------------------

    def _track_dir(self, track_id: str) -> Path:
        return self.library_root / track_id

    def track_file_path(self, track_id: str, filename: str = "track.mp3") -> str:
        """Return the absolute path where a track's file is/should be stored."""
        return str(self._track_dir(track_id) / filename)

    def ensure_track_dir(self, track_id: str) -> Path:
        """Create (if needed) and return the per-track directory."""
        d = self._track_dir(track_id)
        d.mkdir(parents=True, exist_ok=True)
        return d

    # ------------------------------------------------------------------
    # CRUD
    # ------------------------------------------------------------------

    def save(
        self,
        *,
        track_id: Optional[str] = None,
        prompt: str = "",
        lyrics: str = "",
        model: str = "",
        file_path: str = "",
        duration_s: float = 0.0,
        file_size: int = 0,
        mood: str = "",
        genre: str = "",
        lang: str = "",
        tags: Optional[List[str]] = None,
        name: str = "",
    ) -> GeneratedTrack:
        """Insert or update a track.  Returns the saved record.

        If ``track_id`` is None, a new UUID4 is generated.  All fields are
        overwritten on conflict (last write wins).
        """
        tid = track_id or uuid.uuid4().hex
        tags_json = json.dumps(list(tags or []), ensure_ascii=False)
        now = time.time()

        # Resolve file size if file exists and caller didn't provide it
        if (not file_size) and file_path and os.path.exists(file_path):
            file_size = os.path.getsize(file_path)

        with self.lock, self.conn:
            existing = self.conn.execute(
                "SELECT track_id, generated_at, play_count FROM generated_tracks WHERE track_id = ?",
                (tid,),
            ).fetchone()
            if existing:
                generated_at = existing["generated_at"] or now
                play_count = existing["play_count"]
                self.conn.execute(
                    """
                    UPDATE generated_tracks SET
                        name = ?, prompt = ?, lyrics = ?, model = ?,
                        file_path = ?, duration_s = ?, file_size = ?,
                        mood = ?, genre = ?, lang = ?, tags = ?,
                        updated_at = ?
                    WHERE track_id = ?
                    """,
                    (name, prompt, lyrics, model, file_path, duration_s,
                     file_size, mood, genre, lang, tags_json, now, tid),
                )
            else:
                generated_at = now
                play_count = 0
                self.conn.execute(
                    """
                    INSERT INTO generated_tracks (
                        track_id, name, prompt, lyrics, model, file_path,
                        duration_s, file_size, mood, genre, lang, tags,
                        play_count, generated_at, updated_at
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    (tid, name, prompt, lyrics, model, file_path,
                     duration_s, file_size, mood, genre, lang, tags_json,
                     play_count, generated_at, now),
                )

        track = GeneratedTrack(
            track_id=tid, name=name, prompt=prompt, lyrics=lyrics, model=model,
            file_path=file_path, duration_s=duration_s, file_size=file_size,
            mood=mood, genre=genre, lang=lang, tags=list(tags or []),
            play_count=play_count, generated_at=generated_at, updated_at=now,
        )

        # Best-effort: write a meta.json sidecar (handy for debugging and
        # for offline tools that read the library by directory).
        try:
            self.ensure_track_dir(tid)
            meta_path = self._track_dir(tid) / "meta.json"
            with open(meta_path, "w", encoding="utf-8") as fh:
                json.dump(track.to_dict(), fh, ensure_ascii=False, indent=2)
        except Exception as exc:  # noqa: BLE001
            logger.debug("meta.json write failed for %s: %s", tid, exc)

        return track

    def get(self, track_id: str) -> Optional[GeneratedTrack]:
        with self.lock:
            row = self.conn.execute(
                "SELECT * FROM generated_tracks WHERE track_id = ?", (track_id,)
            ).fetchone()
        return self._row_to_track(row) if row else None

    def delete(self, track_id: str) -> bool:
        """Delete the track and its files.  Returns True if found."""
        track = self.get(track_id)
        if not track:
            return False
        with self.lock, self.conn:
            self.conn.execute("DELETE FROM generated_tracks WHERE track_id = ?", (track_id,))
        # Best-effort: remove per-track directory
        try:
            d = self._track_dir(track_id)
            if d.exists():
                import shutil
                shutil.rmtree(d, ignore_errors=True)
        except Exception as exc:  # noqa: BLE001
            logger.warning("Could not remove track dir %s: %s", track_id, exc)
        return True

    def increment_play_count(self, track_id: str) -> int:
        """Atomically bump play_count; returns the new value (-1 if not found)."""
        with self.lock, self.conn:
            cur = self.conn.execute(
                "UPDATE generated_tracks SET play_count = play_count + 1, updated_at = ? "
                "WHERE track_id = ? RETURNING play_count",
                (time.time(), track_id),
            ).fetchone()
        return int(cur["play_count"]) if cur else -1

    # ------------------------------------------------------------------
    # Listing
    # ------------------------------------------------------------------

    def list_recent(self, limit: int = 20, offset: int = 0) -> List[GeneratedTrack]:
        with self.lock:
            rows = self.conn.execute(
                "SELECT * FROM generated_tracks ORDER BY generated_at DESC LIMIT ? OFFSET ?",
                (limit, offset),
            ).fetchall()
        return [self._row_to_track(r) for r in rows]

    def list_popular(self, limit: int = 20, offset: int = 0) -> List[GeneratedTrack]:
        with self.lock:
            rows = self.conn.execute(
                "SELECT * FROM generated_tracks "
                "WHERE play_count > 0 "
                "ORDER BY play_count DESC, generated_at DESC LIMIT ? OFFSET ?",
                (limit, offset),
            ).fetchall()
        return [self._row_to_track(r) for r in rows]

    def list_all(self, limit: int = 20, sort_by: str = "recent", offset: int = 0) -> List[GeneratedTrack]:
        sort_by = (sort_by or "recent").lower()
        if sort_by == "popular":
            return self.list_popular(limit=limit, offset=offset)
        return self.list_recent(limit=limit, offset=offset)

    def count(self) -> int:
        with self.lock:
            row = self.conn.execute("SELECT COUNT(*) AS c FROM generated_tracks").fetchone()
        return int(row["c"]) if row else 0

    # ------------------------------------------------------------------
    # Search (FTS5 + optional vector)
    # ------------------------------------------------------------------

    def search(
        self,
        query: str,
        *,
        tags: Optional[List[str]] = None,
        mood: Optional[str] = None,
        genre: Optional[str] = None,
        limit: int = 5,
    ) -> List[GeneratedTrack]:
        """Hybrid keyword + filter search.

        FTS5 over ``prompt / lyrics / name / mood / genre / tags`` first.
        If it returns fewer than ``FTS_MIN_RESULTS`` and Ollama is
        available, the function falls back to a vector similarity search
        (re-embedding ``prompt + lyrics`` per candidate).  Returns at
        most ``limit`` results.
        """
        query = (query or "").strip()
        if not query and not tags and not mood and not genre:
            return self.list_recent(limit=limit)

        # ── 1. FTS5 candidate set (over-fetch then filter)
        fts_hits: List[GeneratedTrack] = []
        if query:
            fts_query = self._escape_fts(query)
            try:
                with self.lock:
                    rows = self.conn.execute(
                        """
                        SELECT t.* FROM generated_tracks_fts f
                        JOIN generated_tracks t ON t.rowid = f.rowid
                        WHERE generated_tracks_fts MATCH ?
                        ORDER BY rank
                        LIMIT ?
                        """,
                        (fts_query, max(limit * 4, 20)),
                    ).fetchall()
                fts_hits = [self._row_to_track(r) for r in rows]
            except sqlite3.OperationalError as exc:
                # Malformed FTS query — degrade to LIKE search
                logger.debug("FTS5 query failed (%s), falling back to LIKE", exc)
                like = f"%{query}%"
                with self.lock:
                    rows = self.conn.execute(
                        """SELECT * FROM generated_tracks
                           WHERE prompt LIKE ? OR lyrics LIKE ? OR name LIKE ?
                           ORDER BY generated_at DESC LIMIT ?""",
                        (like, like, like, max(limit * 4, 20)),
                    ).fetchall()
                fts_hits = [self._row_to_track(r) for r in rows]
        else:
            # No keyword → start with the most recent N (filter applied below)
            fts_hits = self.list_recent(limit=max(limit * 4, 20))

        # ── 2. Apply tag / mood / genre filters
        filtered = self._apply_filters(fts_hits, tags=tags, mood=mood, genre=genre)

        # ── 3. Top up with LIKE-based text search if still under limit
        if len(filtered) < limit and query:
            seen = {t.track_id for t in filtered}
            like = f"%{query}%"
            with self.lock:
                rows = self.conn.execute(
                    """SELECT * FROM generated_tracks
                       WHERE (prompt LIKE ? OR lyrics LIKE ? OR name LIKE ?)
                       ORDER BY generated_at DESC LIMIT ?""",
                    (like, like, like, max(limit * 2, 10)),
                ).fetchall()
            for r in rows:
                t = self._row_to_track(r)
                if t.track_id in seen:
                    continue
                seen.add(t.track_id)
                if self._matches_filters(t, tags=tags, mood=mood, genre=genre):
                    filtered.append(t)
                if len(filtered) >= limit:
                    break

        return filtered[:limit]

    @staticmethod
    def _escape_fts(query: str) -> str:
        """Wrap each token in double quotes for safe FTS5 MATCH input.

        FTS5 treats hyphens, dots, and several other characters as
        operators; wrapping each word keeps user input safe.
        """
        tokens = [t for t in query.replace('"', ' ').split() if t]
        return " ".join(f'"{t}"' for t in tokens)

    @staticmethod
    def _apply_filters(
        tracks: List[GeneratedTrack],
        tags: Optional[List[str]],
        mood: Optional[str],
        genre: Optional[str],
    ) -> List[GeneratedTrack]:
        return [t for t in tracks if GeneratedMusicLibrary._matches_filters(t, tags=tags, mood=mood, genre=genre)]

    @staticmethod
    def _matches_filters(
        track: GeneratedTrack,
        tags: Optional[List[str]],
        mood: Optional[str],
        genre: Optional[str],
    ) -> bool:
        if mood and mood.lower() not in (track.mood or "").lower():
            return False
        if genre and genre.lower() not in (track.genre or "").lower():
            return False
        if tags:
            tlow = {t.lower() for t in track.tags}
            for want in tags:
                if want.lower() not in tlow:
                    return False
        return True

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _row_to_track(row: sqlite3.Row) -> GeneratedTrack:
        try:
            tags = json.loads(row["tags"] or "[]")
            if not isinstance(tags, list):
                tags = []
        except Exception:
            tags = []
        return GeneratedTrack(
            track_id=row["track_id"],
            name=row["name"] or "",
            prompt=row["prompt"] or "",
            lyrics=row["lyrics"] or "",
            model=row["model"] or "",
            file_path=row["file_path"] or "",
            duration_s=float(row["duration_s"] or 0.0),
            file_size=int(row["file_size"] or 0),
            mood=row["mood"] or "",
            genre=row["genre"] or "",
            lang=row["lang"] or "",
            tags=tags,
            play_count=int(row["play_count"] or 0),
            generated_at=float(row["generated_at"] or 0.0),
            updated_at=float(row["updated_at"] or 0.0),
        )

    def close(self) -> None:
        try:
            self.conn.close()
        except Exception:
            pass


__all__ = ["GeneratedMusicLibrary", "GeneratedTrack"]
