#!/usr/bin/env python3
"""Render Mermaid architecture graphs from static inventory + live ROS 2 runtime evidence."""
from __future__ import annotations

import argparse
import json
import re
from collections import defaultdict
from pathlib import Path

SYSTEM_TOPICS = {"/rosout", "/parameter_events", "/bond"}


def norm(value):
    return re.sub(r"[^a-z0-9]", "", value.lower())


def canonical_node(value):
    """Normalize ROS node names while preserving namespaces."""
    return value.lstrip("/")


def safe(value):
    return (
        value.replace("&", "&amp;")
        .replace('"', "&quot;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def node_class_map(inventory):
    by_norm = defaultdict(list)
    for item in inventory.get("classes", []):
        if not item.get("is_node") or not item.get("name"):
            continue
        name = item["name"]
        key = norm(name)
        for candidate in {key, re.sub(r"node$", "", key)}:
            if candidate:
                by_norm[candidate].append(name)
    return {k: sorted(set(v))[0] for k, v in by_norm.items() if len(set(v)) == 1}


def resolve_class(node, classes):
    key = norm(node.rsplit("/", 1)[-1])
    return classes.get(key) or classes.get(re.sub(r"node$", "", key))


def connected_topics(runtime, include_system=False):
    result = []
    for topic in runtime.get("topics", []):
        if not include_system and topic in SYSTEM_TOPICS:
            continue
        info = runtime.get("topic_info", {}).get(topic, {})
        if info.get("publishers") and info.get("subscribers"):
            result.append(topic)
    return sorted(
        result,
        key=lambda t: (
            -(
                len(runtime.get("topic_info", {}).get(t, {}).get("publishers", []))
                + len(runtime.get("topic_info", {}).get(t, {}).get("subscribers", []))
            ),
            t,
        ),
    )


def resolve_runtime_node(value, runtime_nodes):
    """Map topic-info endpoint names to the captured runtime node identity."""
    node = canonical_node(value)
    if node in runtime_nodes:
        return node
    matches = [candidate for candidate in runtime_nodes if candidate.rsplit("/", 1)[-1] == node]
    if len(matches) == 1:
        return matches[0]
    return node


def compose_services(inventory):
    services = []
    for group in inventory.get("containers", []):
        source = group.get("file", "")
        host = "Vision Pi" if "docker/vision/" in source else "Main Pi" if "docker/main/" in source else "Other"
        for service in group.get("services", []):
            item = dict(service)
            item["host"] = host
            item["source"] = source
            services.append(item)
    return services


def node_owner(node, cls, inventory, services):
    """Best-effort static ownership mapping; never invents runtime ownership."""
    leaf = norm(node.rsplit("/", 1)[-1])
    cls_norm = norm(cls or "")
    scores = []
    for service in services:
        names = {
            norm(service.get("name") or ""),
            norm(service.get("container_name") or ""),
        }
        names.discard("")
        score = 0
        for name in names:
            if leaf == name:
                score = max(score, 100)
            elif cls_norm and cls_norm == name:
                score = max(score, 95)
            elif leaf and name and (leaf in name or name in leaf):
                score = max(score, 70)
            elif cls_norm and name and (cls_norm in name or name in cls_norm):
                score = max(score, 65)
        if score:
            scores.append((score, service))
    if not scores:
        return None
    scores.sort(key=lambda x: (-x[0], x[1].get("host", ""), x[1].get("name", "")))
    if len(scores) > 1 and scores[0][0] == scores[1][0] and scores[0][1].get("host") != scores[1][1].get("host"):
        return None
    return scores[0][1]


def build_graph(runtime, inventory, topics, title):
    runtime_nodes = {canonical_node(x) for x in runtime.get("nodes", []) if x}
    nodes = set(runtime_nodes)

    for topic in topics:
        info = runtime.get("topic_info", {}).get(topic, {})
        for endpoint in info.get("publishers", []) + info.get("subscribers", []):
            value = endpoint.get("node")
            if value:
                nodes.add(resolve_runtime_node(value, runtime_nodes))
    nodes = sorted(nodes)

    classes = node_class_map(inventory)
    services = compose_services(inventory)
    node_meta = {}
    for node in nodes:
        cls = resolve_class(node, classes)
        owner = node_owner(node, cls, inventory, services)
        node_meta[node] = {"class": cls, "owner": owner}

    class_ids = {}
    lines = [
        "%% Auto-generated by tools/architecture_runtime_graph.py",
        "%% Source: architecture/runtime.json + architecture/inventory.json",
        "%% Physical hierarchy: Pi -> container -> node -> class; topics are shared ROS resources",
        '%%{init: {"theme":"neutral","htmlLabels":true,"flowchart":{"curve":"basis"}}}%%',
        "flowchart LR",
    ]

    hosts = {"Main Pi": "10.1.1.20", "Vision Pi": "10.1.1.21"}
    for capture in runtime.get("captures", []):
        if capture.get("pi") and capture.get("host"):
            hosts[capture["pi"]] = capture["host"]
    host_services = defaultdict(list)
    for service in services:
        if service.get("host") in hosts:
            host_services[service["host"]].append(service)

    next_id = 0
    service_ids = {}
    for host, address in hosts.items():
        host_id = f"H{next_id}"
        next_id += 1
        lines.append(f'    subgraph {host_id}["🖥️ {host} @ {address}"]')
        assigned = defaultdict(list)
        for node, meta in node_meta.items():
            owner = meta["owner"]
            if owner and owner.get("host") == host:
                assigned[owner.get("name") or owner.get("container_name")].append(node)

        for service in sorted(host_services[host], key=lambda x: x.get("name", "")):
            service_name = service.get("name") or service.get("container_name") or "container"
            if not assigned.get(service_name):
                continue
            cid = f"C{next_id}"
            next_id += 1
            service_ids[service_name] = cid
            lines.append(f'        subgraph {cid}["🐳 {safe(service_name)}"]')
            for node in sorted(assigned[service_name]):
                nid = f"N{next_id}"
                kid = f"K{next_id}"
                next_id += 1
                cls = node_meta[node]["class"]
                class_label = f"class: {cls}" if cls else "class: unresolved"
                class_ids[node] = kid
                lines.append(f'            subgraph {nid}["{safe(node)}"]')
                lines.append(f'                {kid}["{safe(class_label)}"]:::classNode')
                lines.append("            end")
            lines.append("        end")

        lines.append("    end")

    unresolved = [n for n, m in node_meta.items() if not m["owner"] and n]
    if unresolved:
        uid = f"C{next_id}"
        next_id += 1
        lines.append(f'    subgraph {uid}["🐳 physical ownership unresolved"]')
        for node in sorted(unresolved):
            nid = f"N{next_id}"
            kid = f"K{next_id}"
            next_id += 1
            cls = node_meta[node]["class"]
            class_label = f"class: {cls}" if cls else "class: unresolved"
            class_ids[node] = kid
            lines.append(f'        subgraph {nid}["{safe(node)}"]')
            lines.append(f'            {kid}["{safe(class_label)}"]:::classNode')
            lines.append("        end")
        lines.append("    end")

    topic_ids = {}
    for index, topic in enumerate(topics):
        topic_id = f"P{index}"
        topic_ids[topic] = topic_id
        lines.append(f'    {topic_id}["{safe(topic)}"]:::topicNode')

    for topic in topics:
        info = runtime.get("topic_info", {}).get(topic, {})
        pubs = {
            resolve_runtime_node(x.get("node"), runtime_nodes)
            for x in info.get("publishers", [])
            if x.get("node")
        }
        subs = {
            resolve_runtime_node(x.get("node"), runtime_nodes)
            for x in info.get("subscribers", [])
            if x.get("node")
        }
        for pub in sorted(pubs):
            if pub in class_ids:
                lines.append(f"    {class_ids[pub]} --> {topic_ids[topic]}")
        for sub in sorted(subs):
            if sub in class_ids:
                lines.append(f"    {topic_ids[topic]} --> {class_ids[sub]}")

    lines += [
        "",
        "    classDef title fill:#f7f7f7,stroke:#777,color:#111,font-weight:bold;",
        "    classDef classNode fill:#fff7ed,stroke:#f59e0b,color:#7c2d12,stroke-width:1.2px;",
        "    classDef topicNode fill:#f0fdf4,stroke:#22c55e,color:#14532d,stroke-width:1.2px;",
    ]
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--runtime", type=Path, default=Path("architecture/runtime.json"))
    parser.add_argument("--inventory", type=Path, default=Path("architecture/inventory.json"))
    parser.add_argument("--output-dir", type=Path, default=Path("architecture"))
    parser.add_argument("--overview-topics", type=int, default=12)
    args = parser.parse_args()

    runtime = json.loads(args.runtime.read_text(encoding="utf-8"))
    inventory = json.loads(args.inventory.read_text(encoding="utf-8"))
    args.output_dir.mkdir(parents=True, exist_ok=True)

    all_topics = connected_topics(runtime)
    overview = all_topics[: max(1, args.overview_topics)]

    (args.output_dir / "runtime-graph.mmd").write_text(
        build_graph(
            runtime,
            inventory,
            all_topics,
            "ROB-BOX ROS 2 runtime architecture — full connected graph",
        ),
        encoding="utf-8",
    )
    (args.output_dir / "runtime-overview.mmd").write_text(
        build_graph(
            runtime,
            inventory,
            overview,
            f"ROB-BOX ROS 2 runtime overview — top {len(overview)} connected topics",
        ),
        encoding="utf-8",
    )

    classes = node_class_map(inventory)
    unresolved = sum(resolve_class(n, classes) is None for n in runtime.get("nodes", []))
    services = compose_services(inventory)
    ownership_unresolved = sum(node_owner(n, resolve_class(n, classes), inventory, services) is None for n in runtime.get("nodes", []))
    print(
        json.dumps(
            {
                "runtime_nodes": len(runtime.get("nodes", [])),
                "connected_topics": len(all_topics),
                "overview_topics": len(overview),
                "unresolved_class_nodes": unresolved,
                "unresolved_physical_ownership_nodes": ownership_unresolved,
            },
            ensure_ascii=False,
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
