# RTAB-Map SLAM - использует специализированный базовый образ rtabmap
# Базовый образ уже содержит rtabmap, image-transport и rmw-zenoh-cpp
ARG BASE_IMAGE=rob_box_base:rtabmap
FROM ${BASE_IMAGE}

# Все необходимые зависимости уже установлены в базовом образе

