# RTAB-Map SLAM - использует специализированный базовый образ rtabmap
# Базовый образ уже содержит rtabmap, image-transport и rmw-zenoh-cpp
# Локальная сборка: docker build --build-arg BASE_IMAGE=rob_box_base:rtabmap
ARG BASE_IMAGE=ghcr.io/krikz/rob_box_base:rtabmap
FROM ${BASE_IMAGE}

# Все необходимые зависимости уже установлены в базовом образе

