name: Build Main Pi Services

# Собираем сервисы Main Pi для проверки работоспособности
on:
  push:
    branches:
      - main
    paths:
      - 'docker/main/**'
      - 'src/**'  # URDF и другие исходники
      - '.github/workflows/build-main-services.yml'
  pull_request:
    paths:
      - 'docker/main/**'
      - 'src/**'
  workflow_dispatch:  # Ручной запуск

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ghcr.io/${{ github.repository_owner }}/rob_box

jobs:
  # Robot State Publisher - публикует TF дерево
  build-robot-state-publisher:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-arch builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_PREFIX }}
          tags: |
            type=raw,value=robot-state-publisher
            type=sha,prefix=robot-state-publisher-

      - name: Build and push robot-state-publisher
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/main/robot_state_publisher/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-contexts: |
            docker/main/robot_state_publisher=docker/main/robot_state_publisher

  # RTAB-Map SLAM
  build-rtabmap:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-arch builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_PREFIX }}
          tags: |
            type=raw,value=rtabmap
            type=sha,prefix=rtabmap-

      - name: Build and push rtabmap
        uses: docker/build-push-action@v5
        with:
          context: docker/main/rtabmap
          file: docker/main/rtabmap/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Проверка сборки всех сервисов прошла успешно
  verify-build:
    runs-on: ubuntu-latest
    needs: [build-robot-state-publisher, build-rtabmap]
    steps:
      - name: Verify all builds succeeded
        run: echo "✅ All Main Pi services built successfully!"
